### ISSUE TITLE
ShadowJar not override Jar outputJar.

### ISSUE THREAD

**Issue by IPECTER** [Goooler/shadow#97]
If ShadowJar ouputJar name is same as default name of Jar outputJar. ([project name]-[project version].jar)
outputJar is not ShadowJar outputJar.
It was work on Original shadow repo..

Original ShadowJar can override original outputJar file.
but your fork cant override and make classes files of shadowed dependencies when name is same.

for test
```gradle
tasks.build {
    dependsOn(shadowJar)
}
shadowJar {
    archiveClassifier.set("")
}
```
and build
build/libs/Project.jar
[Goooler](https://github.com/Goooler)/[shadow](https://github.com/Goooler/shadow) -> Original Jar file
[johnrengelman](https://github.com/johnrengelman)/[shadow](https://github.com/johnrengelman/shadow) -> Shadow Jar file

**Comment by Goooler** [comment]
```sh
eza -l .
.rwxr-xr-x 4.3M goooler  8 May 13:22 string-res-exporter-0.3.0-SNAPSHOT-binary.jar
.rw-r--r-- 4.3M goooler  8 May 13:22 string-res-exporter-0.3.0-SNAPSHOT-r8.jar
.rw-r--r--  20M goooler  8 May 13:22 string-res-exporter-0.3.0-SNAPSHOT.jar
```

This works for me. Any reproducer?

**Comment by IPECTER** [comment]
hmm strangy...
I cant decompile shadow jar using your fork
